---
- hosts: servers
  become: true

  tasks:

  - name: Populate service facts
    service_facts:

  - name: install required packages (RPM)
    package:
      name:
        - docker
      state: present
    when: "ansible_distribution == 'RedHat' or ansible_distribution == 'Fedora'"

