---
- hosts: servers
  become: true

  tasks:

  - name: Populate service facts
    service_facts:

  # Only installs the prep stuff if using containers
  - import_role:
      name: fahclient

  - name: Install Docker Version
    include_role:
      name: docker
    tags:
      - docker

  - name: Disable Nouveau Driver
    include_role:
      name: nouveau-blacklist
    tags:
      - gpu
      - nvidia

  - name: Install Nvidia Drivers
    include_role:
      name: nvidia-driver-install
    tags:
      - gpu
      - nvidia

  - name: Install Nvidia OCI Hooks
    include_role:
      name: nvidia-container-runtime-hook
    tags:
      - gpu
      - nvidia
      - container

  - name: Install Radeon Drivers
    include_role:
      name: radeon-driver-install
    tags:
      - gpu
      - radeon

  #TODO: Do we need OCI hooks or something else to enable radeon containers like nvidia?

  # If containerized install deps and start container
  - name: Install Podman Version
    include_role:
      name: podman
    tags:
      - podman
      - container

...
