---
- hosts: all
  become: true
  tasks:

    - name: Make sure python-apt installed on Debian based hosts
      apt:
        name: python-apt
        state: present
        update_cache: true
      when:
        (ansible_distribution == 'Debian') or
        (ansible_distribution == 'Ubuntu')

    - name: Populate service facts
      service_facts:
      tags: always


- hosts: clients
  tasks:

    - name: Include GPU tasks if enabled
      include: gpu.yaml
      static: no
      when: (gpu | bool)

    - import_role:
        name: fahclient

    - import_role:
        name: podman
      when: (podman | bool)

    - import_role:
        name: docker
      when: (docker | bool)

- hosts: controllers
  tasks:

    - import_role:
        name: fahcontroller

- hosts: viewers
  tasks:

    - import_role:
        name: fahviewer

...
