---
- hosts: servers
  become: true

  tasks:

# This way of detecting GPUs is portable and doesn't require root
  - name: check for Nvidia GPU
    shell:
      cmd: awk 'BEGIN{result="false"} $0 ~ /0x10de/ {gsub(/\/vendor/, "/class", FILENAME); getline pciclass < FILENAME; if(pciclass ~ /^0x03/) result="true"}  END{print result}'  /sys/bus/pci/devices/*/vendor
    register: has_nvidia_gpu

  - name: Make sure python-apt installed on Debian based hosts
    apt:
      name: python-apt
      state: present
      update_cache: yes
    when:
      (ansible_distribution == 'Debian') or
      (ansible_distribution == 'Ubuntu')

  - name: Disable Nouveau Driver
    include_role:
      name: nouveau-blacklist
    when:
      (gpu | bool) and
      (has_nvidia_gpu.stdout == "true")

  - name: Install Nvidia Drivers
    include_role:
      name: nvidia-driver-install
    when:
      (gpu | bool) and
      (has_nvidia_gpu.stdout == "true")

  #TODO: Do we need OCI hooks or something else to enable radeon containers like nvidia?
  #TODO: What is needed if using docker instead of podman
  - name: Install Nvidia OCI Hooks
    include_role:
      name: nvidia-container-runtime-hook
    when:
      (gpu | bool) and
      (has_nvidia_gpu.stdout == "true") and
      (gpu_driver == 'cuda') and
      (podman | bool)

  - name: Install OpenCL Drivers
    include_role:
      name: opencl-driver-install
    when:
      (gpu | bool) and
      (gpu_type == 'nvidia') and
      (gpu_driver == 'opencl')

  - name: Install Radeon Drivers
    include_role:
      name: radeon-driver-install
    when:
      (gpu | bool) and
      (gpu_type == 'radeon')

  - name: Populate service facts
    service_facts:
    tags: always

  - include_role:
      name: fahclient
  
  - name: Install and run fahclient with docker
    include_role:
      name: docker
    when:
      docker | bool

  - name: Install and run fahclient with podman
    include_role:
      name: podman
    when:
      (podman | bool)

...
