---
- hosts: servers
  become: true

  tasks:

  - name: Populate service facts
    service_facts:
    tags: always

  - include_role:
      name: fahclient
    
  - name: Disable Nouveau Driver
    include_role:
      name: nouveau-blacklist
    when:
      (gpu | bool) and
      (gpu_type == 'nvidia')

  - name: Install Nvidia Drivers
    include_role:
      name: nvidia-driver-install
    when:
      (gpu | bool) and
      (gpu_type == 'nvidia')

  #TODO: Do we need OCI hooks or something else to enable radeon containers like nvidia?
  - name: Install Nvidia OCI Hooks
    include_role:
      name: nvidia-container-runtime-hook
    when:
      (gpu | bool) and
      (gpu_type == 'nvidia') and
      (containerized | bool)

  - name: Install Radeon Drivers
    include_role:
      name: radeon-driver-install
    when:
      (gpu | bool) and
      (gpu_type == 'radeon')

  - name: Install fahclient as a docker image
    include_role:
      name: docker
    when:
      containerized | bool

  - name: Install Podman Version
    include_role:
      name: podman
    when:
      (containerized | bool)

...
