---
# This needs to be fixed to ensure that the kernel-devel packages
# is exactly the same as the kernel. If there is a kernel upgrade
# you get the latest kernel-devel but the old kernel and the Nvidia
# drivers don't install
- name: install kernel-devel
  package:
    name: kernel-devel-{{ ansible_kernel }}
    state: present

- name: install EPEL
  package:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present
  when: "ansible_distribution == 'RedHat'"

- name: install RPMFusion
  package:
    name: https://download1.rpmfusion.org/free/el/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present
  when: "ansible_distribution == 'RedHat'"

- name: install RPMFusion
  package:
    name: https://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present
  when: "ansible_distribution == 'RedHat'"

#- name: install OpenCL drivers
#  package:
#    name: opencl
#    state: present
#  when: "ansible_distribution == 'RedHat'"
