---

# There appears to be an issue with switching to the fahclient user
# to run podman rootless. Using sudo to change to another user, which is what
# ansible is doing, doesn't work with podman
- name: Pull the fahclient container image
  podman_image:
    name: quay.io/fah/fah-client
    tag: "v{{ fahclient_ver }}"

- name: Start fahclient container
  shell: |
    podman run -d -p '7396:7396' -p '36330:36330' -v /etc/fahclient:/etc/fahclient:Z \
               -v /var/lib/fahclient:/var/lib/fahclient:Z --cpus={{ cpus }} \
               --name fahclient --userns=keep-id "quay.io/fah/fah-client:v{{ fahclient_ver }}"
