---

# There appears to be an issue with switching to the fahclient user
# to run podman rootless. Using sudo to change to another user, which is what
# ansible is doing, doesn't work with podman
- name: Pull the cuda enabled fahclient container image
  docker_image:
    name: quay.io/fah/fah-client-cuda
    tag: "v{{ fahclient_ver }}"
    state: present
    source: pull

- name: Run the fahclient docker image
  docker_container:
    name: fahclient
    image: "quay.io/fah/fah-client-cuda:v{{ fahclient_ver }}"
    detach: true
    volumes:
      - /etc/fahclient:/etc/fahclient:Z
      - /var/lib/fahclient:/var/lib/fahclient:Z
    ports:
      - 7396:7396
      - 36330:36330
# TODO: Add cap drop for security
#    cap_drop:
#      - all
#    capabilities:
#      - sys_time
