---

product: fahviewer

url: https://download.foldingathome.org/releases
beta: beta/release/{{ product }}
public: public/release/{{ product }}

fah_viewer_pkgs:
  Debian:
    '7.4.15': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.4/{{ product }}-7.4.15-1.x86_64.rpm'
    '7.4.16': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.4/{{ product }}-7.4.16-1.x86_64.rpm'
    '7.4.17': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.4/{{ product }}-7.4.17-1.x86_64.rpm'
    '7.4.18': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.4/{{ product }}-7.4.18-1.x86_64.rpm'
    '7.5.0': '{{ url }}/{{ public }}/debian-stable-64bit/v7.5/{{ product }}_7.5.0_amd64.deb'
    '7.5.1': '{{ url }}/{{ public }}/debian-stable-64bit/v7.5/{{ product }}_7.5.1_amd64.deb'
    '7.6.0': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.0_amd64.deb'
    '7.6.1': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.1_amd64.deb'
    '7.6.2': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.2_amd64.deb'
    '7.6.3': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.3_amd64.deb'
    '7.6.4': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.4_amd64.deb'
    '7.6.5': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.5_amd64.deb'
    '7.6.6': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.6_amd64.deb'
    '7.6.7': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.7_amd64.deb'
    '7.6.8': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.8_amd64.deb'
    '7.6.9': '{{ url }}/{{ public }}/debian-stable-64bit/v7.6/{{ product }}_7.6.9_amd64.deb'
    '7.6.10': '{{ url }}/{{ public }}/debian-stable-64bit/v7.6/{{ product }}_7.6.10_amd64.deb'
    '7.6.11': '{{ url }}/{{ public }}/debian-stable-64bit/v7.6/{{ product }}_7.6.11_amd64.deb'
    '7.6.12': '{{ url }}/{{ public }}/debian-stable-64bit/v7.6/{{ product }}_7.6.12_amd64.deb'
    '7.6.13': '{{ url }}/{{ public }}/debian-stable-64bit/v7.6/{{ product }}_7.6.13_amd64.deb'
    'latestbeta':   '{{ url }}/{{ public }}/debian-stable-64bit/v7.6/latest.deb'
    'latestpublic': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/latest.deb'

  Ubuntu:
    '7.4.15': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.4/{{ product }}-7.4.15-1.x86_64.rpm'
    '7.4.16': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.4/{{ product }}-7.4.16-1.x86_64.rpm'
    '7.4.17': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.4/{{ product }}-7.4.17-1.x86_64.rpm'
    '7.4.18': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.4/{{ product }}-7.4.18-1.x86_64.rpm'
    '7.5.0': '{{ url }}/{{ public }}/debian-stable-64bit/v7.5/{{ product }}_7.5.0_amd64.deb'
    '7.5.1': '{{ url }}/{{ public }}/debian-stable-64bit/v7.5/{{ product }}_7.5.1_amd64.deb'
    '7.6.0': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.0_amd64.deb'
    '7.6.1': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.1_amd64.deb'
    '7.6.2': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.2_amd64.deb'
    '7.6.3': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.3_amd64.deb'
    '7.6.4': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.4_amd64.deb'
    '7.6.5': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.5_amd64.deb'
    '7.6.6': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.6_amd64.deb'
    '7.6.7': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.7_amd64.deb'
    '7.6.8': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/{{ product }}_7.6.8_amd64.deb'
    '7.6.9': '{{ url }}/{{ public }}/debian-stable-64bit/v7.6/{{ product }}_7.6.9_amd64.deb'
    '7.6.10': '{{ url }}/{{ public }}/debian-stable-64bit/v7.6/{{ product }}_7.6.10_amd64.deb'
    '7.6.11': '{{ url }}/{{ public }}/debian-stable-64bit/v7.6/{{ product }}_7.6.11_amd64.deb'
    '7.6.12': '{{ url }}/{{ public }}/debian-stable-64bit/v7.6/{{ product }}_7.6.12_amd64.deb'
    '7.6.13': '{{ url }}/{{ public }}/debian-stable-64bit/v7.6/{{ product }}_7.6.13_amd64.deb'
    'latestbeta':   '{{ url }}/{{ public }}/debian-stable-64bit/v7.6/latest.deb'
    'latestpublic': '{{ url }}/{{ beta }}/debian-stable-64bit/v7.6/latest.deb'


  Fedora:
    '7.4.15': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.4.15-1.x86_64.rpm'
    '7.4.16': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.4.16-1.x86_64.rpm'
    '7.4.17': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.4.17-1.x86_64.rpm'
    '7.4.18': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.4.18-1.x86_64.rpm'
    '7.5.0': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.5.0-1.x86_64.rpm'
    '7.5.1': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.5.1-1.x86_64.rpm'
    '7.6.0': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.0-1.x86_64.rpm'
    '7.6.1': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.1-1.x86_64.rpm'
    '7.6.2': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.2-1.x86_64.rpm'
    '7.6.3': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.3-1.x86_64.rpm'
    '7.6.4': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.4-1.x86_64.rpm'
    '7.6.5': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.5-1.x86_64.rpm'
    '7.6.6': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.6-1.x86_64.rpm'
    '7.6.7': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.7-1.x86_64.rpm'
    '7.6.8': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.8-1.x86_64.rpm'
    '7.6.9': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.9-1.x86_64.rpm'
    '7.6.10': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.10-1.x86_64.rpm'
    '7.6.11': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.11-1.x86_64.rpm'
    '7.6.12': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.12-1.x86_64.rpm'
    '7.6.13': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.13-1.x86_64.rpm'
    'latestbeta': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/latest.rpm'
    'latestpublic': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/latest.rpm'




  RedHat:
    '7.4.15': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.4.15-1.x86_64.rpm'
    '7.4.16': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.4.16-1.x86_64.rpm'
    '7.4.17': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.4.17-1.x86_64.rpm'
    '7.4.18': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.4.18-1.x86_64.rpm'
    '7.5.0': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.5.0-1.x86_64.rpm'
    '7.5.1': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.5.1-1.x86_64.rpm'
    '7.6.0': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.0-1.x86_64.rpm'
    '7.6.1': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.1-1.x86_64.rpm'
    '7.6.2': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.2-1.x86_64.rpm'
    '7.6.3': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.3-1.x86_64.rpm'
    '7.6.4': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.4-1.x86_64.rpm'
    '7.6.5': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.5-1.x86_64.rpm'
    '7.6.6': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.6-1.x86_64.rpm'
    '7.6.7': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.7-1.x86_64.rpm'
    '7.6.8': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.8-1.x86_64.rpm'
    '7.6.9': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.9-1.x86_64.rpm'
    '7.6.10': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.10-1.x86_64.rpm'
    '7.6.11': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.11-1.x86_64.rpm'
    '7.6.12': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.12-1.x86_64.rpm'
    '7.6.13': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.13-1.x86_64.rpm'
    'latestbeta': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/latest.rpm'
    'latestpublic': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/latest.rpm'


  CentOS:
    '7.4.15': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.4.15-1.x86_64.rpm'
    '7.4.16': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.4.16-1.x86_64.rpm'
    '7.4.17': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.4.17-1.x86_64.rpm'
    '7.4.18': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.4.18-1.x86_64.rpm'
    '7.5.0': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.5.0-1.x86_64.rpm'
    '7.5.1': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.5.1-1.x86_64.rpm'
    '7.6.0': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.0-1.x86_64.rpm'
    '7.6.1': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.1-1.x86_64.rpm'
    '7.6.2': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.2-1.x86_64.rpm'
    '7.6.3': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.3-1.x86_64.rpm'
    '7.6.4': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.4-1.x86_64.rpm'
    '7.6.5': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.5-1.x86_64.rpm'
    '7.6.6': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.6-1.x86_64.rpm'
    '7.6.7': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.7-1.x86_64.rpm'
    '7.6.8': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.8-1.x86_64.rpm'
    '7.6.9': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.9-1.x86_64.rpm'
    '7.6.10': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.10-1.x86_64.rpm'
    '7.6.11': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.11-1.x86_64.rpm'
    '7.6.12': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.12-1.x86_64.rpm'
    '7.6.13': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.13-1.x86_64.rpm'
    'latestbeta': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/latest.rpm'
    'latestpublic': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/latest.rpm'

  Amazon:
    '7.4.15': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.4.15-1.x86_64.rpm'
    '7.4.16': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.4.16-1.x86_64.rpm'
    '7.4.17': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.4.17-1.x86_64.rpm'
    '7.4.18': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.4.18-1.x86_64.rpm'
    '7.5.0': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.5.0-1.x86_64.rpm'
    '7.5.1': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.5/{{ product }}-7.5.1-1.x86_64.rpm'
    '7.6.0': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.0-1.x86_64.rpm'
    '7.6.1': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.1-1.x86_64.rpm'
    '7.6.2': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.2-1.x86_64.rpm'
    '7.6.3': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.3-1.x86_64.rpm'
    '7.6.4': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.4-1.x86_64.rpm'
    '7.6.5': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.5-1.x86_64.rpm'
    '7.6.6': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.6-1.x86_64.rpm'
    '7.6.7': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.7-1.x86_64.rpm'
    '7.6.8': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.8-1.x86_64.rpm'
    '7.6.9': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.9-1.x86_64.rpm'
    '7.6.10': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.10-1.x86_64.rpm'
    '7.6.11': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.11-1.x86_64.rpm'
    '7.6.12': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.12-1.x86_64.rpm'
    '7.6.13': '{{ url }}/{{ public }}/centos-6.7-64bit/v7.6/{{ product }}-7.6.13-1.x86_64.rpm'
    'latestbeta': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/latest.rpm'
    'latestpublic': '{{ url }}/{{ beta }}/centos-6.7-64bit/v7.6/latest.rpm'

