---
- hosts: servers
  become: true

  tasks:

  - name: Ensure group "fahclient" exists
    group:
      name: fahclient
      state: present
      system: true
    when: "ansible_distribution == 'RedHat' or ansible_distribution == 'Fedora' or ansible_distribution == 'Amazon'"

  - name: Ensure user "fahclient" exists
    user:
      name: fahclient
      state: present
      group: fahclient
      comment: "Folding@home Client"
      shell: /bin/bash
      expires: -1
      system: false
    when: "ansible_distribution == 'RedHat' or ansible_distribution == 'Fedora' or ansible_distribution == 'Amazon'"

  - name: Create fahclient directories
    file:
      path: "{{ item }}"
      state: directory
      owner: fahclient
      group: fahclient
      mode: 0775
    with_items:
      - /var/lib/fahclient
      - /etc/fahclient
    when: "ansible_distribution == 'RedHat' or ansible_distribution == 'Fedora' or ansible_distribution == 'Amazon'"

  - name: Install FaH config
    template:
      src: sample-config.xml.j2
      dest: /etc/fahclient/config.xml

  - name: Install Podman Version
    include_role:
      name: podman
    tags:
      - podman
