---
- hosts: servers
  become: true

  tasks:

  - name: Populate service facts
    service_facts:

  - name: install required packages (RPM)
    package:
      name:
        - podman
      state: present
    when: "ansible_distribution == 'RedHat' or ansible_distribution == 'Fedora'"

  - name: Gather package facts
    package_facts:
      manager: auto

  - name: Ensure group "fahclient" exists
    group:
      name: fahclient
      state: present
      system: true
    when: "ansible_distribution == 'RedHat' or ansible_distribution == 'Fedora' or ansible_distribution == 'Amazon'"

  - name: Ensure user "fahclient" exists
    user:
      name: fahclient
      state: present
      group: fahclient
      comment: "Folding@home Client"
      shell: /bin/bash
      expires: -1
      system: false
    when: "ansible_distribution == 'RedHat' or ansible_distribution == 'Fedora' or ansible_distribution == 'Amazon'"

  - name: Create fahclient directories
    file:
      path: "{{ item }}"
      state: directory
      owner: fahclient
      group: fahclient
      mode: 0775
    with_items:
      - /var/lib/fahclient
      - /etc/fahclient
    when: "ansible_distribution == 'RedHat' or ansible_distribution == 'Fedora' or ansible_distribution == 'Amazon'"

  - name: Install FaH config
    template:
      src: sample-config.xml.j2
      dest: /etc/fahclient/config.xml

# There appears to be an issue with switching to the fahclient user
# to run podman rootless. Using sudo to change to another user, which is what
# ansible is doing, doesn't work with podman
  - name: Pull the fahclient container image
    podman_image:
      name: quay.io/fah/fah-client
      tag: v7.5.1

  - name: Start fahclient container
    shell: podman run -d -p '7396:7396' -p '36330:36330' -v /etc/fahclient:/etc/fahclient:Z -v /var/lib/fahclient:/var/lib/fahclient:Z --cpus={{ cpus }} --name fahclient --userns=keep-id quay.io/fah/fah-client:v7.5.1

  - name: Generate systemd service to startup fahclient pod on boot
    shell: podman generate systemd --name --restart-policy=no fahclient > /etc/systemd/system/FAHClient.service

  - name: Start and enable FaH client
    service:
      name: FAHClient
      daemon_reload: true
      enabled: true
      state: started

