---
- hosts: servers
  become: true

  tasks:

  - name: Ensure group "fahclient" exists
    group:
      name: fahclient
      state: present
      system: true
    when: "ansible_distribution == 'RedHat' or ansible_distribution == 'Fedora' or ansible_distribution == 'Amazon'"

  - name: Ensure user "fahclient" exists
    user:
      name: fahclient
      state: present
      group: fahclient
      comment: "Folding@home Client"
      shell: /bin/bash
      expires: -1
      system: false
    when: "ansible_distribution == 'RedHat' or ansible_distribution == 'Fedora' or ansible_distribution == 'Amazon'"

  - name: Create fahclient directories
    file:
      path: "{{ item }}"
      state: directory
      owner: fahclient
      group: fahclient
      mode: 0775
    with_items:
      - /var/lib/fahclient
      - /etc/fahclient
    when: "ansible_distribution == 'RedHat' or ansible_distribution == 'Fedora' or ansible_distribution == 'Amazon'"

  - name: Install FaH config
    template:
      src: sample-config.xml.j2
      dest: /etc/fahclient/config.xml

  - name: Disable Nouveau Driver
    include_role:
      name: nouveau-blacklist
    tags:
      - gpu
      - nvidia
    when: gpu and 'gpu_type == nvidia'

  - name: Install Nvidia Drivers
    include_role:
      name: nvidia-driver-install
    tags:
      - gpu
      - nvidia
    when: gpu and 'gpu_type == nvidia'

  - name: Install Nvidia OCI Hooks
    include_role:
      name: nvidia-container-runtime-hook
    tags:
      - gpu
      - nvidia
      - container
    when: gpu and containerized and 'gpu_type == nvidia'

  - name: Install Radeon Drivers
    include_role:
      name: radeon-driver-install
    tags:
      - gpu
      - radeon
    when: gpu and 'gpu_type == radeon'

  #TODO: Do we need OCI hooks or something else to enable radeon containers like nvidia?


  # If containerized install deps and start container
  - name: Install Podman Version
    include_role:
      name: podman
    tags:
      - podman
      - container
    when: containerized


