---

- name: Gather package facts
  package_facts:
    manager: auto

# TODO: This will not work on RHEL 6 because RHEL 6 cannot validate
# F@H's SSL Certificates
- name: download packages for the FaH Viewer
  get_url:
    url: "{{ (fah_viewer_pkgs[ ansible_distribution ])[fahviewer_ver] }}"
    dest: /tmp
  when:
    ('fahviewer' not in ansible_facts.packages)

- name: install FaH packages (RPM)
  command: "rpm -ivh --nodeps --noscripts /tmp/{{ item | regex_replace( '^http.*/', '' ) }}"
  with_items: "{{ fah_viewer_pkgs[ ansible_distribution ][ fahviewer_ver ] }}"
  when:
    ('fahviewer' not in ansible_facts.packages) and
    ( ansible_distribution == 'RedHat' or ansible_distribution == 'Fedora' or ansible_distribution == 'CentOS' or ansible_distribution == 'Amazon' )

- name: install FaH packages (DEB)
  apt:
    deb: "/tmp/{{ item | regex_replace( 'http.*/', '' ) }}"
  with_items: "{{ fah_viewer_pkgs[ ansible_distribution ][ fahviewer_ver ] }}"
  when:
    ('fahviewer' not in ansible_facts.packages) and
    (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')

